version: "3.9"
services:
  app:
    build: ./infra/php
    volumes:
      - ./src:/data

  web:
    build: ./infra/nginx
    ports:
      - '8080:80'
    volumes:
      - ./src:/data
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
  
  db:
    build: ./infra/mysql
    volumes:
      - ./infra/mysql/db-store:/var/lib/mysql
    ports:
      - '3306:3306'